#!/usr/bin/env node
'use strict';

/**
 * Build data/weeks/recent-history.json — a ~1 KB summary of what the last few weeks used.
 *
 * Cross-week variety previously had no mechanism at all: the generation skill forbids
 * reading existing week files (to keep input cheap), so nothing stopped a dinner from
 * repeating week after week. W25 and W26 shared 4 of 26 slots including the same salmon
 * dinner. This file is small enough to feed into generation, and validate-plan.js reads
 * it to reject protein/starch pairings reused too recently.
 *
 * Usage
 *   node scripts/derive-history.js              # newest 6 weeks
 *   node scripts/derive-history.js --weeks 10
 */

const fs   = require('fs');
const path = require('path');
const { analyze, MAIN_SLOTS } = require('./lib/analyze.js');

const WEEKS_DIR = path.join(__dirname, '..', 'data', 'weeks');
const OUT_PATH  = path.join(WEEKS_DIR, 'recent-history.json');

const args  = process.argv.slice(2);
const nIdx  = args.indexOf('--weeks');
const limit = nIdx !== -1 ? Number(args[nIdx + 1]) || 4 : 4;

const files = fs.readdirSync(WEEKS_DIR)
  .filter(f => /^\d{4}-W\d{2}\.json$/.test(f))
  .sort()
  .reverse()
  .slice(0, limit);

const weeks = [];

for (const file of files) {
  let data;
  try {
    data = JSON.parse(fs.readFileSync(path.join(WEEKS_DIR, file), 'utf8'));
  } catch (err) {
    console.warn(`[WARN] skipping ${file}: ${err.message}`);
    continue;
  }

  const A = analyze(data);
  if (A.problems.length) {
    // Legacy weeks may use ingredient names that predate the catalog. Summarise what we can.
    console.warn(`[WARN] ${file}: ${A.problems.length} ingredient(s) unresolved — summary may be partial`);
  }

  const dinnerIds = [...new Set(data.menu.map(d => d.dinner?.recipe_id).filter(Boolean))];
  const pairings  = [];
  const proteins  = new Set();
  const grains    = new Set();

  for (const id of dinnerIds) {
    const f = A.recipeFacts.get(id);
    if (!f) continue;
    if (f.proteinItem) proteins.add(f.proteinItem);
    if (f.grainBase)   grains.add(f.grainBase);
    if (f.proteinItem && f.grainBase) pairings.push(`${f.proteinItem}+${f.grainBase}`);
  }

  const bases = new Set();
  const snackFormats = new Set();
  for (const day of data.menu) {
    const b = A.recipeFacts.get(day.breakfast?.recipe_id)?.recipe.base;
    if (b) bases.add(b);
    const s = A.recipeFacts.get(day.shared_snack?.recipe_id)?.recipe.snack_format;
    if (s) snackFormats.add(s);
  }

  weeks.push({
    id: data.week.id,
    start_date: data.week.start_date,
    dinner_titles:    data.menu.map(d => d.dinner?.title).filter(Boolean),
    dinner_pairings:  [...new Set(pairings)],
    dinner_proteins:  [...proteins],
    grain_bases:      [...grains],
    breakfast_bases:  [...bases],
    snack_formats:    [...snackFormats]
  });
}

const out = {
  schema_version: '1.0',
  _comment: 'Auto-generated by scripts/derive-history.js — do not hand-edit. Newest week first.',
  weeks
};

fs.writeFileSync(OUT_PATH, JSON.stringify(out, null, 2), 'utf8');

const bytes = fs.statSync(OUT_PATH).size;
console.log(`Wrote ${weeks.length} week summary/ies to ${path.relative(process.cwd(), OUT_PATH)} (${bytes} bytes)`);
weeks.forEach(w => console.log(`  ${w.id}: ${w.dinner_pairings.length} dinner pairing(s), bases [${w.breakfast_bases.join(', ') || '—'}]`));
